services:
  - type: web
    name: dogs-web-api
    env: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_HOST
        fromDatabase:
          name: dogs-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: dogs-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: dogs-db
          property: database
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: dogs-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: dogs-db
          property: password

databases:
  - name: dogs-db
    plan: free
    region: singapore
    databaseName: dogsdb
    user: dogsuser
